# Generated by Django 4.2 on 2025-08-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='rule',
            field=models.CharField(default='staff', max_length=50),
        ),
    ]
